6.7. Получение данных из форм
htmlacademy-php/964637-yeticave-12 pull request #12
Opened 2022-08-14 11:57 UTC by LickurG

2022-08-16 18:25 UTC, alexey3017 reviewed
Соответственно часть функционала не сделана, поэтому я описал, будут вопросы пиши

2022-08-16 18:25 UTC, sky-aleks commented on add.php
> +$is_auth = rand(0, 1);
лучше пиши random_int, действия одинаковые но эта более новая

2022-08-16 18:25 UTC, sky-aleks commented on add.php
> +//error_reporting(0);
не оставляй закоментированый код, за чистотой следить обязательно

2022-08-16 18:25 UTC, sky-aleks commented on add.php
> +require_once('validate_func.php');
подключение файлов делай лучше в самом верху, залог чистого кода

2022-08-16 18:25 UTC, sky-aleks commented on add.php
> +}
if ($_FILES['lot_img'] && $_FILES['lot_img']['size'] === 0) {
    $addLotErr['lot_img'] = 'Фаил небыл выбран';
} else if (mime_content_type($_FILES['lot_img']['tmp_name']) !== 'image/jpeg' && mime_content_type($_FILES['lot_img']['tmp_name']) !== 'image/png') {
    $addLotErr['lot_img'] = 'Неверный формат файла';
} else {
    $file_name = $_FILES['lot_img']['name'];
    $file_path = __DIR__ . '\uploads\\';
}

if (!move_uploaded_file($_FILES['lot_img']['tmp_name'], $file_path . $file_name)) {
    $addLotErr['lot_img'] = 'Не удалось загрузить фаил';
} - как минимум в данной проверке можно было сократить вложенности и получилась бы следующая кострукция и так же не оставляй магические числа

2022-08-16 18:25 UTC, sky-aleks commented on add.php
> +if (isset($_POST['submit']) && count($addLotErr) == 0) {
делай строгие проверки count($addLotErr) === 0 -  и не допускай магические числа, лучше вынеси число 0  в переменную

2022-08-16 18:25 UTC, sky-aleks commented on helpers.php
> +    $userPrice = ceil((int) $userPrice);
а какой смысл твоей замены int $userPrice ? по факту тут был типизирован аргумент, в твоем случае лучше было при вызове данной функции убедиться что передаем число

2022-08-16 18:25 UTC, sky-aleks commented on helpers.php
> +    if (!isset($_POST['category_id']) or $_POST['category_id'] == 0) {
так же магическое число

2022-08-16 18:25 UTC, sky-aleks commented on add.php
> +    var_dump($addLot);
дампы и принты.и прочее в коде оставлять нельзя только если это не требовалось либо это какой то роут конкретно для дебага

2022-08-16 18:25 UTC, alexey3017 commented on add.php
> +}
а что такое поле submit? у тебя его нет ты попадешь в данный файл на событие submit  у формы и соответственно в данном файле в методе POST должны быть твои данные типа POST['name']

2022-08-16 18:25 UTC, alexey3017 commented on templates/add.php
> +          <span class="form__error">Не введено наименование лота</span>
почитай про методы  filter_input, filter_input_array

2022-09-15 18:14 UTC, dionisvl requested changes

2022-09-15 18:14 UTC, dionisvl commented on bd2.sql
> +-- --------------------------------------------------------
ну вообще файл должен называться schema.sql

2022-09-15 18:14 UTC, dionisvl commented on bd2.sql
> +-- Хост:                         127.0.0.1
проект не запускается, в файле queries.sql - Ошибка:
`SQL Error [1054] [42S22]: Unknown column 'completion_dt' in 'field list'`

2022-09-15 18:14 UTC, dionisvl commented on add.php
> +require_once('config.php');
по PSR тут должна быть пустая строка после тега <?php

2022-09-15 18:14 UTC, dionisvl commented on add.php
> +$id = filter_input(INPUT_GET, 'id', FILTER_SANITIZE_NUMBER_INT);
$id - не соответсвует критерию Б3
надо переименовать в $lot_id

2022-09-15 18:14 UTC, dionisvl commented on add.php
> +$emptyError = 0;
в этой переменной нет никакого смысла. Лучше её удалить а там где она используется написать 0.

2022-09-15 18:14 UTC, dionisvl commented on add.php
> +        echo '<meta http-equiv="Refresh" content="0; URL=lot.php?id=' . $getAddedLot . '">';
это довольно плохой вариант редиректа. 
предпочтительней сделать на стороне бекенда, на PHP , типа 
```
header("Location: lot.php?id=". $getAddedLot);
die();
```
Тут подробности как и что https://stackoverflow.com/questions/768431/how-do-i-make-a-redirect-in-php

2022-09-15 18:14 UTC, dionisvl commented on config.php
> +﻿<?php
пароли нельзя хранить в открытом виде,
надо удалить этот файл из репозитория. а вместо него добавить в репозиторий файл типа `config.php.example`

2022-09-15 18:20 UTC, dionisvl commented on add.php
> +}
@LickurG да, нельзя ориентироваться на поле $_POST['submit']
При попадании в файл add.php нужно проверять чтобы были правильно заполнены вообще все обязательные поля.

2022-10-19 12:04 UTC, merged